apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: intrachat-dev-image-updater
  namespace: argocd
spec:
  namespace: argocd
  commonUpdateSettings:
    updateStrategy: "digest"
    pullSecret: "pullsecret:argocd/ghcr-credentials"
  writeBackConfig:
    method: "git"
    gitConfig:
      branch: "main"
      repository: "https://github.com/MichelEloka/Intrachat.git"
      writeBackTarget: "kustomization:."
  applicationRefs:
    - namePattern: "intrachat-dev"
      images:
        - alias: "webfrontend"
          imageName: "ghcr.io/micheleloka/intrachat-web-frontend:latest"
          manifestTargets:
            kustomize:
              name: "intrachat/web-frontend"
        - alias: "authservice"
          imageName: "ghcr.io/micheleloka/intrachat-auth-service:latest"
          manifestTargets:
            kustomize:
              name: "intrachat/auth-service"
