apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres
  labels:
    app.kubernetes.io/name: keycloak-postgres
    app.kubernetes.io/part-of: intrachat
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: keycloak-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
