apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgres-data
  labels:
    app.kubernetes.io/name: keycloak-postgres
    app.kubernetes.io/part-of: intrachat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
