apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intrachat-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MichelEloka/Intrachat.git
    targetRevision: main
    path: gitops/env/staging/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
